### ISSUE TITLE
Touch events

### ISSUE THREAD

**Issue by jimfrenette-icrossing** [VincentCharpentier/krousel#2]
Enhancement request: please add touch events to be able to swipe the slides.

**Comment by VincentCharpentier** [comment]
Hi @jimfrenette-icrossing ,

Sure that's in the scope.

I'll try to add this soon

**Comment by VincentCharpentier** [comment]
Hi @jimfrenette-icrossing ,

I've been working on adding the swipe option, it is the main improvement in v0.2.0 I just pushed.

You can test it here: https://vincentcharpentier.github.io/krousel/

I'll try to do a bit more testing be I release this version on npm (should be today anyway)

Let me know if you find any bug or weird behavior.

**Comment by VincentCharpentier** [comment]
Swiping is now working well, I recommend using the lastest version available on npm.

Closing this issue as solved, thank you for your input 👍

**Comment by jimfrenette-icrossing** [comment]
This is great news. Thanks!
